# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('fiscalSign', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('nds18', models.IntegerField(default=-1)),
                ('taxation_type', models.IntegerField(default=-1)),
                ('ecash_total_sum', models.IntegerField(default=-1)),
                ('cashTotalSum', models.IntegerField(default=-1)),
                ('total_sum', models.IntegerField(default=-1)),
                ('operationType', models.IntegerField(default=-1)),
                ('qr', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('cashback', models.IntegerField(default=-1)),
                ('in_processing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
