# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('nds18', models.IntegerField()),
                ('taxation_type', models.IntegerField()),
                ('ecash_total_sum', models.IntegerField()),
                ('cashTotalSum', models.IntegerField()),
                ('total_sum', models.IntegerField()),
                ('operationType', models.CharField(max_length=100)),
                ('qr', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('cashback', models.IntegerField()),
                ('in_processing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('cashback', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.BillItem'),
        ),
    ]
