# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20170918_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='operationType',
            field=models.IntegerField(default=-1),
        ),
    ]
