# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='fiscalSign',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
