# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20170918_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.BillItem'),
        ),
    ]
