# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20170918_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='item',
        ),
        migrations.AddField(
            model_name='billitem',
            name='bills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bill.Bill'),
            preserve_default=False,
        ),
    ]
