# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20170918_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='cashback',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.IntegerField(default=-1),
        ),
    ]
