# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20170918_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='bill.Bill'),
        ),
    ]
