# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20170919_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bills',
        ),
    ]
