# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_remove_billitem_bills'),
        ('items', '0004_auto_20170919_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
