# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(null=True)),
                ('price', models.IntegerField(default=-1)),
                ('cashback', models.IntegerField(default=-1)),
                ('bills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.Bill')),
            ],
        ),
    ]
