# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20170918_2011'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bill_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bill.BillItem'),
            preserve_default=False,
        ),
    ]
