# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
