# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_bill_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bill_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.BillItem'),
        ),
    ]
