# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_remove_billitem_bills'),
        ('items', '0003_auto_20170919_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bill_items',
        ),
        migrations.AddField(
            model_name='item',
            name='bills',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.Bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cashback',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=-1),
        ),
    ]
