# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20170919_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.Bill'),
        ),
    ]
