# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_cashback', models.IntegerField(default=0)),
                ('current_cashback', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('bills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
